//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Modula2.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IModula2Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class Modula2BaseListener : IModula2Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] Modula2Parser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] Modula2Parser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] Modula2Parser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] Modula2Parser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.varStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarStatement([NotNull] Modula2Parser.VarStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.varStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarStatement([NotNull] Modula2Parser.VarStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] Modula2Parser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] Modula2Parser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] Modula2Parser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] Modula2Parser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.ifBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfBlock([NotNull] Modula2Parser.IfBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.ifBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfBlock([NotNull] Modula2Parser.IfBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.elseIfBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseIfBlock([NotNull] Modula2Parser.ElseIfBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.elseIfBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseIfBlock([NotNull] Modula2Parser.ElseIfBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.elseBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseBlock([NotNull] Modula2Parser.ElseBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.elseBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseBlock([NotNull] Modula2Parser.ElseBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] Modula2Parser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] Modula2Parser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.procedureDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureDeclaration([NotNull] Modula2Parser.ProcedureDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.procedureDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureDeclaration([NotNull] Modula2Parser.ProcedureDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.procedureCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureCall([NotNull] Modula2Parser.ProcedureCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.procedureCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureCall([NotNull] Modula2Parser.ProcedureCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.varFormal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarFormal([NotNull] Modula2Parser.VarFormalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.varFormal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarFormal([NotNull] Modula2Parser.VarFormalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] Modula2Parser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] Modula2Parser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] Modula2Parser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] Modula2Parser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.negateOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegateOp([NotNull] Modula2Parser.NegateOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.negateOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegateOp([NotNull] Modula2Parser.NegateOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] Modula2Parser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] Modula2Parser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] Modula2Parser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] Modula2Parser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.arrayAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAccess([NotNull] Modula2Parser.ArrayAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.arrayAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAccess([NotNull] Modula2Parser.ArrayAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.arrayIndexAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayIndexAccess([NotNull] Modula2Parser.ArrayIndexAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.arrayIndexAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayIndexAccess([NotNull] Modula2Parser.ArrayIndexAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.ident"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdent([NotNull] Modula2Parser.IdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.ident"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdent([NotNull] Modula2Parser.IdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] Modula2Parser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] Modula2Parser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray([NotNull] Modula2Parser.ArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray([NotNull] Modula2Parser.ArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.realNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRealNumber([NotNull] Modula2Parser.RealNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.realNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRealNumber([NotNull] Modula2Parser.RealNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] Modula2Parser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] Modula2Parser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.addOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddOp([NotNull] Modula2Parser.AddOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.addOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddOp([NotNull] Modula2Parser.AddOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.multOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultOp([NotNull] Modula2Parser.MultOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.multOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultOp([NotNull] Modula2Parser.MultOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCharacter([NotNull] Modula2Parser.CharacterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCharacter([NotNull] Modula2Parser.CharacterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Modula2Parser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] Modula2Parser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Modula2Parser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] Modula2Parser.StringContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
